int _putchar(char c);
void print_alphabet(void);
void print_alpahbet_x10(void);
int _islower(int c);
int _isalpha(intc c);
int print_sign(int c);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
int add(int, int);
print_to_98(int n);
void print_times_table(int n);
